#!/bin/bash

CHANGE_THEME_SCRIPT_DIR=${CHANGE_THEME_SCRIPT_DIR:="$HOME/.config/mythemes"}

QTILE_THEME_DIR=${QTILE_THEME_DIR:="$HOME/.config/qtile"}
KITTY_THEME_DIR=${KITTY_THEME_DIR:="$HOME/.config/kitty"}
NVIM_THEME_DIR=${NVIM_THEME_DIR:="$HOME/.config/nvim"}
STARSHIP_THEME_DIR=${STARSHIP_THEME_DIR:="$HOME/.config"}

QTILE_FILE=${QTILE_FILE:="config.py"}
KITTY_FILE=${KITTY_FILE:="kitty.conf"}
NVIM_FILE=${NVIM_FILE:="init.lua"}
STARSHIP_FILE=${STARSHIP_FILE:="starship.toml"}

THEME_CHOICE=$(cat $CHANGE_THEME_SCRIPT_DIR/themes.txt | dmenu)

mv $QTILE_THEME_DIR/$QTILE_FILE $QTILE_THEME_DIR/$QTILE_FILE.bak
mv $KITTY_THEME_DIR/$KITTY_FILE $KITTY_THEME_DIR/$KITTY_FILE.bak
mv $NVIM_THEME_DIR/$NVIM_FILE $NVIM_THEME_DIR/$NVIM_FILE.bak
mv $STARSHIP_THEME_DIR/$STARSHIP_FILE $STARSHIP_THEME_DIR/$STARSHIP_FILE.bak

cp $CHANGE_THEME_SCRIPT_DIR/themes/qtile/$THEME_CHOICE.py $QTILE_THEME_DIR/$QTILE_FILE
cp $CHANGE_THEME_SCRIPT_DIR/themes/kitty/$THEME_CHOICE.conf $KITTY_THEME_DIR/$KITTY_FILE
cp $CHANGE_THEME_SCRIPT_DIR/themes/nvim/$THEME_CHOICE.lua $NVIM_THEME_DIR/$NVIM_FILE
cp $CHANGE_THEME_SCRIPT_DIR/themes/starship/$THEME_CHOICE.toml $STARSHIP_THEME_DIR/$STARSHIP_FILE

# If nitrogen is installed
nitrogen --set-zoom-fill --save $CHANGE_THEME_SCRIPT_DIR/themes/wallpapers/$THEME_CHOICE.*
