#!/bin/bash

QTILE_THEME_DIR=${QTILE_THEME_DIR:="$HOME/.config/qtile"}
KITTY_THEME_DIR=${KITTY_THEME_DIR:="$HOME/.config/kitty"}
NVIM_THEME_DIR=${NVIM_THEME_DIR:="$HOME/.config/nvim"}
STARSHIP_THEME_DIR=${STARSHIP_THEME_DIR:="$HOME/.config"}

QTILE_FILE=${QTILE_FILE:="config.py"}
KITTY_FILE=${KITTY_FILE:="kitty.conf"}
NVIM_FILE=${NVIM_FILE:="init.lua"}
STARSHIP_FILE=${STARSHIP_FILE:="starship.toml"}

cp $QTILE_THEME_DIR/$QTILE_FILE.bak $QTILE_THEME_DIR/$QTILE_FILE.old
cp $KITTY_THEME_DIR/$KITTY_FILE.bak $KITTY_THEME_DIR/$KITTY_FILE.old
cp $NVIM_THEME_DIR/$NVIM_FILE.bak $NVIM_THEME_DIR/$NVIM_FILE.old
cp $STARSHIP_THEME_DIR/$STARSHIP_FILE.bak $STARSHIP_THEME_DIR/$STARSHIP_FILE.old

mv $QTILE_THEME_DIR/$QTILE_FILE.bak $QTILE_THEME_DIR/$QTILE_FILE
mv $KITTY_THEME_DIR/$KITTY_FILE.bak $KITTY_THEME_DIR/$KITTY_FILE
mv $NVIM_THEME_DIR/$NVIM_FILE.bak $NVIM_THEME_DIR/$NVIM_FILE
mv $STARSHIP_THEME_DIR/$STARSHIP_FILE.bak $STARSHIP_THEME_DIR/$STARSHIP_FILE
